### ISSUE TITLE
Encryption error

### ISSUE THREAD

**Issue by dartymath** [eavanvalkenburg/sia#28]
Dear All,

since this morning, i loose my connection with my Hub2. The connection work only when i remove the encrytion ! i try different new or old encryption without success !!
I don't understand where is coming from !

any ideas ?

**Comment by eavanvalkenburg** [comment]
Could you turn on logging and post some logs, I can't really debug this!

**Comment by dartymath** [comment]
How did i can turn on logging ?

**Comment by eavanvalkenburg** [comment]
In your configuration add this:
```yaml
logger:
  default: error
  logs:
    custom_components.sia: debug 
    pysiaalarm: debug
```
