### ISSUE TITLE
Event timestamp is no longer valid

### ISSUE THREAD

**Issue by jyourstone** [eavanvalkenburg/sia#46]
## Version of the custom_component and HA setup (version, OS, etc)

SIA v0.5.0-beta.6
Home Asistant 2021.5.1
Supervisor 2021.04.3
Home Assistant OS 5.13

## Configuration

```yaml

                "entry_id": "xxx",
                "version": 2,
                "domain": "sia",
                "title": "SIA Alarm on port 8124",
                "data": {
                    "accounts": [
                        {
                            "account": "xxx",
                            "encryption_key": "xxx",
                            "ping_interval": 1,
                            "zones": 1
                        }
                    ],
                    "port": 8124,
                    "protocol": "TCP"
                },
                "options": {},
                "system_options": {
                    "disable_new_entities": false
                },
                "source": "user",
                "connection_class": "local_push",
                "unique_id": "sia_8124",
                "disabled_by": null
```

## Describe the bug
Not sure if this happened after Ajax updated itself, but all of a sudden I cannot see the status of Ajax in Home Assistant anymore and in the Ajax app it says that the alarm central is disconnected.

The log file is filled with warnings (at the moment just 45 occurences since I just restarted HA to enable log debugging).

## Debug log

```text

Logger: pysiaalarm.base_server
Source: /usr/local/lib/python3.8/site-packages/pysiaalarm/base_server.py:126
First occurred: 8:37:33 AM (45 occurrences)
Last logged: 8:45:28 AM

Event timestamp is no longer valid: 2021-05-09 06:47:23+00:00
Event timestamp is no longer valid: 2021-05-09 06:47:33+00:00
Event timestamp is no longer valid: 2021-05-09 06:47:43+00:00
Event timestamp is no longer valid: 2021-05-09 06:47:53+00:00
Event timestamp is no longer valid: 2021-05-09 06:48:04+00:00

---

2021-05-09 08:37:33 DEBUG (MainThread) [pysiaalarm.base_server] Incoming line: xxx
2021-05-09 08:37:33 DEBUG (MainThread) [pysiaalarm.event] Content matches: {'account': 'xxx', 'ti': None, 'id': None, 'ri': '1', 'code': 'OP', 'message': '1', 'xdata': None, 'timestamp': '06:40:08,05-09-2021'}
2021-05-09 08:37:33 WARNING (MainThread) [pysiaalarm.base_server] Event timestamp is no longer valid: 2021-05-09 06:40:08+00:00

```
