### ISSUE TITLE
Lack of configuration info

### ISSUE THREAD

**Issue by vincenzosuraci** [eavanvalkenburg/sia#7]
I installed your component using HACS. It does not work. 
I guess it's my fault: probably I did something wrong in the Ajax Hub configuration I did using the mobile app.

To configure your component, I copied and pasted on `configuration.yaml` the following code taken from [here](https://community.home-assistant.io/t/ajax-alarm-system/62853/44)

```
sia:
  port:  port
  hubs:
    - name: hubname
      account: account
      encryption_key: password
      zones:
        - zone: 1
          name: zonename
          sensors:
           - alarm
           - moisture
           - smoke
```
In particular, I have the following questions:
1. `port` is a port number that I can invent (e.g. 4628)?
2. `account` is the username used to get access on the mobile app?
3. `password` is the password of the mobile app, or is the encryption key described [here](https://support.ajax.systems/en/how-to-use-sia-for-cms-connection)?

I also guess that, in order to make a Hub interwork with your custom component, it is necessary also to configure it using the mobile App (e.g. following these instructions [here](https://support.ajax.systems/en/how-to-use-sia-for-cms-connection)). What it is not clear to me are the following additional configuration items:

4. The `port` of the SIA protocol must be the same of the one defined in Home Assistant, at point 1.?
5. The under the `Primary ip address` section, the `Ip address` must be setup to be the ip address of the machine hosting Home Assistant, right?
6. The under the `Primary ip address` section, the `Port` must be setup to be the http port of the machine hosting Home Assistant (whose default value is 8123), right?

Without these precious information, it is rather difficult to successfully install and make your wonderful component work.

Regards,
Vincenzo
